name: Terraform Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.0

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v4
      with:
        tflint_version: 0.52.0
    
    - name: Init TFLint
      run: tflint --init
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: false

    - name: Run TFLint
      run: tflint -f compact
      continue-on-error: false
    
    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: |
        terraform plan -no-color -input=false -lock-timeout=60s -out=tfplan
        terraform show -json -no-color tfplan > tfplan.json
      id: plan
      continue-on-error: false

    - name: Upload tfplan.json as artifact
      uses: actions/upload-artifact@v4
      with:
        name: tfplan-json
        path: tfplan.json

    - name: Terraform Apply
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve